// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201162428_InitialCrea121te")]
    partial class InitialCrea121te
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.UserAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("IpAddress");

                    b.Property<DateTime>("Local")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Local");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TimeZone");

                    b.Property<DateTime>("UTC")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTC");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("UserAgent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserAction");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DAL.Entities.LoginStatistic", b =>
                {
                    b.HasBaseType("DAL.Entities.UserAction");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceTypeId");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("StatusTypeId");

                    b.HasIndex("UTC");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "UTC");

                    b.ToTable("LoginStatistics", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.LogoutStatistic", b =>
                {
                    b.HasBaseType("DAL.Entities.UserAction");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceTypeId");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("StatusTypeId");

                    b.HasIndex("UTC");

                    b.HasIndex("UserId");

                    b.ToTable("LogoutStatistics", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.RegistrationStatistic", b =>
                {
                    b.HasBaseType("DAL.Entities.UserAction");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceTypeId");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("StatusTypeId");

                    b.HasIndex("UTC");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationStatistics", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.LoginStatistic", b =>
                {
                    b.HasOne("DAL.Entities.UserAction", null)
                        .WithOne()
                        .HasForeignKey("DAL.Entities.LoginStatistic", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.LogoutStatistic", b =>
                {
                    b.HasOne("DAL.Entities.UserAction", null)
                        .WithOne()
                        .HasForeignKey("DAL.Entities.LogoutStatistic", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.RegistrationStatistic", b =>
                {
                    b.HasOne("DAL.Entities.UserAction", null)
                        .WithOne()
                        .HasForeignKey("DAL.Entities.RegistrationStatistic", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
